language: ruby
before_script:
  - psql -c 'create database pgapp_test;' -U postgres
  - bundle exec rails db:migrate RAILS_ENV=test

script: bundle exec rspec

# gives access to a postgres instance
services:
  - postgresql
